apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv-zoo
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual # Ensure this matches your PVC's storage class
  hostPath: # Use appropriate volume type for your environment
    path: /path/on/host-zoo